### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sipkode** [aquila-lab/superflex-vscode#7] opened 2024-10-01 21:38 UTC
Today I started to get frequent "500 Internal Server Error"s when submitting a query.  It will sometimes go away on its own after waiting a while.  Signing out and signing in a few times seems to make it go away faster...

No other error output is visible.

**Comment by Riphal** [comment] 2024-10-03 21:40
Hey @sipkode!

Thanks a lot for reporting it and for your patience!

We had an issue with our vector storage, which caused about 3 hours of downtime. Everything’s back to normal now, and we’re really sorry for any inconvenience this might have caused.

We're constantly working on improving our product, so sometimes these hiccups happen as we push new updates and fixes.

Since the issue is resolved, I’ll go ahead and close it. If anything else comes up, feel free to reopen it or create a new one!

**Closed by Riphal** 2024-10-03 21:40 UTC
