### ISSUE TITLE
Can't attach images inside dev container

### ISSUE THREAD

**Issue by sipkode** [aquila-lab/superflex-vscode#6] opened 2024-09-26 20:58 UTC
When trying to attach an image, it fails and gives an error like this:

`ENOENT: no such file or directory, open '/vscode/vscode-server/bin/linux-x64/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/C:\Users\<username>\Pictures\Screenshots\Screenshot 2024-09-26 165339.png'`

Weirdly, it still shows up in the feed...

I'm running my VS Code environment inside a dev container.

VS Code version: 1.93.1

**Comment by Riphal** [comment] 2024-09-27 10:49
Hey @sipkode, first I want to officially thank you for being the first person to open an issue for Superflex! 🤩

I think I have an idea why this happened. I will take a look at how to resolve it and then come back to you if I need more information.

**Comment by sipkode** [comment] 2024-10-01 20:38
Thanks for looking into it @Riphal!  It also appears that code files aren't being attached in this environment either. :(  It shows that the current file is attached automatically, and doesn't show any errors when I submit a query, but it also is unable to answer questions about the file and seems to not understand the context unless I manually copy-paste the body of the file into the prompt box.

**Comment by Riphal** [comment] 2024-10-03 21:43
Looks like we need to revisit how we're handling code indexing when users are working in a virtual environment. Apologies for the delayed response, there’s been a lot happening lately. I will be looking into this issue soon and will keep you updated on the progress!

**Comment by PRANJALRANA11** [comment] 2024-10-24 06:52
@Riphal can i look into this issue to solve

**Comment by Riphal** [comment] 2024-10-25 15:42
Yeah sure I just assigned this one to you too

**Comment by PRANJALRANA11** [comment] 2024-10-27 15:19
> Thanks for looking into it @Riphal! It also appears that code files aren't being attached in this environment either. :( It shows that the current file is attached automatically, and doesn't show any errors when I submit a query, but it also is unable to answer questions about the file and seems to not understand the context unless I manually copy-paste the body of the file into the prompt box.

@sipkode after several tries it's not reproducible file context are working on my end ! please check with the latest version if you are facing issue then also then please comment down your container.json config

**Closed** 2024-10-28 21:26 UTC
Labels: bug
